name: Build and Publish
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Setup Java 1.8 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

    #  - name: Make envfile
    #    uses: SpicyPizza/create-envfile@v1
    #    with:
      #    envkey_SELF_URL: https://alxgrk.github.io/new-relic-hackathon-firewatcher/
     #     envkey_API_URL: https://firewatcher-backend.herokuapp.com/
     #     directory: frontend

      # Build application
      - name: Build
        env:
          SELF_URL: https://firewatcher-backend.herokuapp.com/
          API_URL: https://firewatcher-backend.herokuapp.com/
        run: cd frontend/ && ./gradlew build

      # If main branch update, deploy to gh-pages
      - name: Deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: frontend/build/distributions # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

